# Generated by Django 4.2.1 on 2023-05-19 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='women_jacket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.women_jacket'),
        ),
        migrations.AddField(
            model_name='cart',
            name='women_joggers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.women_joggers'),
        ),
        migrations.AddField(
            model_name='cart',
            name='women_pants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.women_pants'),
        ),
        migrations.AddField(
            model_name='cart',
            name='women_shirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.women_shirt'),
        ),
    ]
